package nl.mpcjanssen.simpletask.dao.gentodo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.gentodo.TodoItem;

import nl.mpcjanssen.simpletask.dao.gentodo.TodoItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoItemDaoConfig;

    private final TodoItemDao todoItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoItemDaoConfig = daoConfigMap.get(TodoItemDao.class).clone();
        todoItemDaoConfig.initIdentityScope(type);

        todoItemDao = new TodoItemDao(todoItemDaoConfig, this);

        registerDao(TodoItem.class, todoItemDao);
    }
    
    public void clear() {
        todoItemDaoConfig.getIdentityScope().clear();
    }

    public TodoItemDao getTodoItemDao() {
        return todoItemDao;
    }

}
