package nl.mpcjanssen.simpletask.dao.gentodo;

import nl.mpcjanssen.simpletask.task.Task;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TODO_ITEM".
 */
public class TodoItem {

    private long line;
    private Task task;
    private boolean selected;

    public TodoItem() {
    }

    public TodoItem(long line) {
        this.line = line;
    }

    public TodoItem(long line, Task task, boolean selected) {
        this.line = line;
        this.task = task;
        this.selected = selected;
    }

    public long getLine() {
        return line;
    }

    public void setLine(long line) {
        this.line = line;
    }

    public Task getTask() {
        return task;
    }

    public void setTask(Task task) {
        this.task = task;
    }

    public boolean getSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

}
