package nl.mpcjanssen.simpletask.dao.gentodo;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.TaskPropertyConverter;
import nl.mpcjanssen.simpletask.task.Task;

import nl.mpcjanssen.simpletask.dao.gentodo.TodoItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TODO_ITEM".
*/
public class TodoItemDao extends AbstractDao<TodoItem, Long> {

    public static final String TABLENAME = "TODO_ITEM";

    /**
     * Properties of entity TodoItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Line = new Property(0, long.class, "line", true, "LINE");
        public final static Property Task = new Property(1, String.class, "task", false, "TASK");
        public final static Property Selected = new Property(2, boolean.class, "selected", false, "SELECTED");
    };

    private final TaskPropertyConverter taskConverter = new TaskPropertyConverter();

    public TodoItemDao(DaoConfig config) {
        super(config);
    }
    
    public TodoItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TODO_ITEM\" (" + //
                "\"LINE\" INTEGER PRIMARY KEY NOT NULL ," + // 0: line
                "\"TASK\" TEXT," + // 1: task
                "\"SELECTED\" INTEGER NOT NULL );"); // 2: selected
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TODO_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TodoItem entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLine());
 
        Task task = entity.getTask();
        if (task != null) {
            stmt.bindString(2, taskConverter.convertToDatabaseValue(task));
        }
        stmt.bindLong(3, entity.getSelected() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public TodoItem readEntity(Cursor cursor, int offset) {
        TodoItem entity = new TodoItem( //
            cursor.getLong(offset + 0), // line
            cursor.isNull(offset + 1) ? null : taskConverter.convertToEntityProperty(cursor.getString(offset + 1)), // task
            cursor.getShort(offset + 2) != 0 // selected
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TodoItem entity, int offset) {
        entity.setLine(cursor.getLong(offset + 0));
        entity.setTask(cursor.isNull(offset + 1) ? null : taskConverter.convertToEntityProperty(cursor.getString(offset + 1)));
        entity.setSelected(cursor.getShort(offset + 2) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(TodoItem entity, long rowId) {
        entity.setLine(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(TodoItem entity) {
        if(entity != null) {
            return entity.getLine();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
