package nl.mpcjanssen.simpletask.dao.todo;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.todo.TodoItem;
import nl.mpcjanssen.simpletask.dao.todo.ArchiveItem;

import nl.mpcjanssen.simpletask.dao.todo.TodoItemDao;
import nl.mpcjanssen.simpletask.dao.todo.ArchiveItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoItemDaoConfig;
    private final DaoConfig archiveItemDaoConfig;

    private final TodoItemDao todoItemDao;
    private final ArchiveItemDao archiveItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoItemDaoConfig = daoConfigMap.get(TodoItemDao.class).clone();
        todoItemDaoConfig.initIdentityScope(type);

        archiveItemDaoConfig = daoConfigMap.get(ArchiveItemDao.class).clone();
        archiveItemDaoConfig.initIdentityScope(type);

        todoItemDao = new TodoItemDao(todoItemDaoConfig, this);
        archiveItemDao = new ArchiveItemDao(archiveItemDaoConfig, this);

        registerDao(TodoItem.class, todoItemDao);
        registerDao(ArchiveItem.class, archiveItemDao);
    }
    
    public void clear() {
        todoItemDaoConfig.getIdentityScope().clear();
        archiveItemDaoConfig.getIdentityScope().clear();
    }

    public TodoItemDao getTodoItemDao() {
        return todoItemDao;
    }

    public ArchiveItemDao getArchiveItemDao() {
        return archiveItemDao;
    }

}
