package nl.mpcjanssen.simpletask.dao.todo;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.todo.TodoItem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TODO_ITEM".
*/
public class TodoItemDao extends AbstractDao<TodoItem, Void> {

    public static final String TABLENAME = "TODO_ITEM";

    /**
     * Properties of entity TodoItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Line = new Property(0, int.class, "line", false, "LINE");
        public final static Property Json = new Property(1, String.class, "json", false, "JSON");
        public final static Property Selected = new Property(2, boolean.class, "selected", false, "SELECTED");
    };


    public TodoItemDao(DaoConfig config) {
        super(config);
    }
    
    public TodoItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TODO_ITEM\" (" + //
                "\"LINE\" INTEGER NOT NULL ," + // 0: line
                "\"JSON\" TEXT NOT NULL ," + // 1: json
                "\"SELECTED\" INTEGER NOT NULL );"); // 2: selected
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TODO_ITEM\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, TodoItem entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getLine());
        stmt.bindString(2, entity.getJson());
        stmt.bindLong(3, entity.getSelected() ? 1L: 0L);
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public TodoItem readEntity(Cursor cursor, int offset) {
        TodoItem entity = new TodoItem( //
            cursor.getInt(offset + 0), // line
            cursor.getString(offset + 1), // json
            cursor.getShort(offset + 2) != 0 // selected
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, TodoItem entity, int offset) {
        entity.setLine(cursor.getInt(offset + 0));
        entity.setJson(cursor.getString(offset + 1));
        entity.setSelected(cursor.getShort(offset + 2) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(TodoItem entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(TodoItem entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
