package nl.mpcjanssen.simpletask.dao.todo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TODO_ITEM".
 */
public class TodoItem {

    private int line;
    /** Not-null value. */
    private String json;
    private boolean selected;

    public TodoItem() {
    }

    public TodoItem(int line, String json, boolean selected) {
        this.line = line;
        this.json = json;
        this.selected = selected;
    }

    public int getLine() {
        return line;
    }

    public void setLine(int line) {
        this.line = line;
    }

    /** Not-null value. */
    public String getJson() {
        return json;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJson(String json) {
        this.json = json;
    }

    public boolean getSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

}
