package nl.mpcjanssen.simpletask.dao.app;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.app.TodoBackup;
import nl.mpcjanssen.simpletask.dao.app.LogItem;

import nl.mpcjanssen.simpletask.dao.app.TodoBackupDao;
import nl.mpcjanssen.simpletask.dao.app.LogItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoBackupDaoConfig;
    private final DaoConfig logItemDaoConfig;

    private final TodoBackupDao todoBackupDao;
    private final LogItemDao logItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoBackupDaoConfig = daoConfigMap.get(TodoBackupDao.class).clone();
        todoBackupDaoConfig.initIdentityScope(type);

        logItemDaoConfig = daoConfigMap.get(LogItemDao.class).clone();
        logItemDaoConfig.initIdentityScope(type);

        todoBackupDao = new TodoBackupDao(todoBackupDaoConfig, this);
        logItemDao = new LogItemDao(logItemDaoConfig, this);

        registerDao(TodoBackup.class, todoBackupDao);
        registerDao(LogItem.class, logItemDao);
    }
    
    public void clear() {
        todoBackupDaoConfig.getIdentityScope().clear();
        logItemDaoConfig.getIdentityScope().clear();
    }

    public TodoBackupDao getTodoBackupDao() {
        return todoBackupDao;
    }

    public LogItemDao getLogItemDao() {
        return logItemDao;
    }

}
