package nl.mpcjanssen.simpletask.dao.app;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TODO_BACKUP".
 */
public class TodoBackup {

    /** Not-null value. */
    private String contents;
    /** Not-null value. */
    private java.util.Date date;

    public TodoBackup() {
    }

    public TodoBackup(String contents) {
        this.contents = contents;
    }

    public TodoBackup(String contents, java.util.Date date) {
        this.contents = contents;
        this.date = date;
    }

    /** Not-null value. */
    public String getContents() {
        return contents;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
