#!/usr/bin/env tclsh
package require ncgi
package require http
::ncgi::parse
::ncgi::header
puts "<html>"
catch {
set uuid [::ncgi::value uuid ""]

if {$uuid eq ""} {
	exit 0
}

set mail_cmd [open "|mailx -r \"Simpletask ticket <ticket@mpcjanssen.nl>\" -s \"Updated ticket [string range $uuid 0 7]\" mpc.janssen@gmail.com" w]

set body "http://mpcjanssen.nl/fossil/simpletask/tktview/$uuid"
puts $mail_cmd $body
close $mail_cmd
} error

puts $error
puts "</html>"
