#!/usr/bin/env tclsh
package require ncgi
package require http
package require sqlite3
::ncgi::parse
::ncgi::header
puts "<html>"
catch {
set uuid [::ncgi::value uuid ""]

if {$uuid eq ""} {
	exit 0
}


sqlite3 db /var/repos/simpletask.fossil -readonly 1

set result [db eval {SELECT title from ticket where tkt_uuid=$uuid}]
set title [lindex $result 0]
db close

if {$env(REMOTE_ADDR) eq "127.0.0.1"} {
   set mail_cmd [open "|mailx -r \"Simpletask ticket <ticket@mpcjanssen.nl>\" -s \"Updated ticket [string range $uuid 0 7]: $title\" mpc.janssen@gmail.com" w]

   set body "http://mpcjanssen.nl/fossil/simpletask/tktview/$uuid"
   puts $mail_cmd $body
   close $mail_cmd
} else {
   puts $env(REMOTE_ADDR)
   puts [ncgi::nvlist]
   puts $title
}
} error

puts $error
puts "</html>"
