#!/usr/bin/env tclsh
package require ncgi
package require http
::ncgi::parse
::ncgi::header

proc send_simple_message {recipient email_server subject body} {
    package require smtp
    package require mime

    set token [mime::initialize -canonical text/plain -string $body]
    mime::setheader $token Subject $subject
    smtp::sendmessage $token -originator "Simpletask ticket <ticket@mpcjanssen.nl>" -recipients $recipient -servers $email_server
    mime::finalize $token
}

puts "<html>"
set uuid [::ncgi::value uuid ""]
set title [::ncgi::value title ""]
set status [::ncgi::value status ""]
set project [::ncgi::value project ""]

if {$env(REMOTE_ADDR) eq "127.0.0.1"} {
   send_simple_message mpc.janssen@gmail.com 127.0.0.1 "Ticket \[[string range $uuid 0 5]\] ($status): $title " "http://mpcjanssen.nl/fossil/$project/tktview/$uuid"
}
puts "</html>"
