package nl.mpcjanssen.simpletask.dao.genbackup;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.genbackup.TodoFile;

import nl.mpcjanssen.simpletask.dao.genbackup.TodoFileDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todoFileDaoConfig;

    private final TodoFileDao todoFileDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todoFileDaoConfig = daoConfigMap.get(TodoFileDao.class).clone();
        todoFileDaoConfig.initIdentityScope(type);

        todoFileDao = new TodoFileDao(todoFileDaoConfig, this);

        registerDao(TodoFile.class, todoFileDao);
    }
    
    public void clear() {
        todoFileDaoConfig.getIdentityScope().clear();
    }

    public TodoFileDao getTodoFileDao() {
        return todoFileDao;
    }

}
