package nl.mpcjanssen.simpletask.dao.genlog;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import nl.mpcjanssen.simpletask.dao.genlog.LogItem;

import nl.mpcjanssen.simpletask.dao.genlog.LogItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig logItemDaoConfig;

    private final LogItemDao logItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        logItemDaoConfig = daoConfigMap.get(LogItemDao.class).clone();
        logItemDaoConfig.initIdentityScope(type);

        logItemDao = new LogItemDao(logItemDaoConfig, this);

        registerDao(LogItem.class, logItemDao);
    }
    
    public void clear() {
        logItemDaoConfig.getIdentityScope().clear();
    }

    public LogItemDao getLogItemDao() {
        return logItemDao;
    }

}
